// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZPCPjtVRSUnO02L2FXQPgi5G9yqb4dA',
    appId: '1:769349365162:web:f1e4a83a6d1ff07b008fd3',
    messagingSenderId: '769349365162',
    projectId: 'survey-71650',
    authDomain: 'survey-71650.firebaseapp.com',
    storageBucket: 'survey-71650.firebasestorage.app',
    measurementId: 'G-LWRWDXKV4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFDMqnumR8oqF_5Q-VNepjrbWajnseV14',
    appId: '1:769349365162:android:c3f635ba1721e544008fd3',
    messagingSenderId: '769349365162',
    projectId: 'survey-71650',
    storageBucket: 'survey-71650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKFRlH8vmD27IXpF522p3FDTlGi8DL240',
    appId: '1:769349365162:ios:52b2f49ce84ee7a1008fd3',
    messagingSenderId: '769349365162',
    projectId: 'survey-71650',
    storageBucket: 'survey-71650.firebasestorage.app',
    iosBundleId: 'com.example.studentQuestionnaire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKFRlH8vmD27IXpF522p3FDTlGi8DL240',
    appId: '1:769349365162:ios:52b2f49ce84ee7a1008fd3',
    messagingSenderId: '769349365162',
    projectId: 'survey-71650',
    storageBucket: 'survey-71650.firebasestorage.app',
    iosBundleId: 'com.example.studentQuestionnaire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtZPCPjtVRSUnO02L2FXQPgi5G9yqb4dA',
    appId: '1:769349365162:web:cecc4c24179a6c7f008fd3',
    messagingSenderId: '769349365162',
    projectId: 'survey-71650',
    authDomain: 'survey-71650.firebaseapp.com',
    storageBucket: 'survey-71650.firebasestorage.app',
    measurementId: 'G-MDSS1YEJPE',
  );
}
